# Generated by Django 5.2.7 on 2026-02-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('value', models.CharField(max_length=255, verbose_name='Valor')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('config_type', models.CharField(choices=[('string', 'Texto'), ('number', 'Número'), ('boolean', 'Booleano')], default='string', max_length=20, verbose_name='Tipo de Dato')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='Categoría')),
                ('is_editable', models.BooleanField(default=True, verbose_name='Editable')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['category', 'key'],
            },
        ),
    ]
