# Generated by Django 5.2.7 on 2026-02-10 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Año de Programación')),
                ('area', models.CharField(max_length=200, verbose_name='Área a Inspeccionar')),
                ('inspection_type', models.CharField(max_length=200, verbose_name='Tipo de Inspección')),
                ('frequency', models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Cuatrimestral', 'Cuatrimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=20, verbose_name='Frecuencia')),
                ('scheduled_date', models.DateField(verbose_name='Fecha Programada')),
                ('status', models.CharField(choices=[('Programada', 'Programada'), ('Realizada', 'Realizada'), ('Pendiente', 'Pendiente')], default='Programada', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Cronograma de Inspección',
                'verbose_name_plural': 'Cronogramas de Inspección',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
