# Generated by Django 5.2.7 on 2026-02-10 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionschedule',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.CreateModel(
            name='ExtinguisherInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Fecha de Inspección')),
                ('area', models.CharField(max_length=200, verbose_name='Área/Ubicación')),
                ('general_status', models.CharField(choices=[('Cumple', 'Cumple'), ('No Cumple', 'No Cumple'), ('No Aplica', 'No Aplica')], default='Cumple', max_length=20, verbose_name='Estado General')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Inspector')),
            ],
            options={
                'verbose_name': 'Inspección de Extintores',
                'verbose_name_plural': 'Inspecciones de Extintores',
                'ordering': ['-inspection_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtinguisherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación Específica')),
                ('extinguisher_type', models.CharField(choices=[('PQS', 'Polvo Químico Seco'), ('CO2', 'Dióxido de Carbono'), ('SOLKAFLAM', 'Solkaflam'), ('AGUA', 'Agua a Presión')], max_length=20, verbose_name='Tipo')),
                ('capacity', models.CharField(max_length=50, verbose_name='Capacidad (lbs/kg)')),
                ('last_recharge_date', models.DateField(blank=True, null=True, verbose_name='Última Recarga')),
                ('next_recharge_date', models.DateField(blank=True, null=True, verbose_name='Próxima Recarga')),
                ('pressure_gauge_ok', models.BooleanField(default=True, verbose_name='Manómetro')),
                ('safety_pin_ok', models.BooleanField(default=True, verbose_name='Seguro/Pasador')),
                ('hose_nozzle_ok', models.BooleanField(default=True, verbose_name='Manguera/Boquilla')),
                ('signage_ok', models.BooleanField(default=True, verbose_name='Señalización')),
                ('access_ok', models.BooleanField(default=True, verbose_name='Acceso Libre')),
                ('label_ok', models.BooleanField(default=True, verbose_name='Etiqueta Legible')),
                ('status', models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('Recargar', 'Recargar')], default='Bueno', max_length=20, verbose_name='Estado')),
                ('observations', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.extinguisherinspection')),
            ],
        ),
        migrations.CreateModel(
            name='FirstAidInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Fecha de Inspección')),
                ('area', models.CharField(max_length=200, verbose_name='Área/Ubicación')),
                ('general_status', models.CharField(choices=[('Cumple', 'Cumple'), ('No Cumple', 'No Cumple'), ('No Aplica', 'No Aplica')], default='Cumple', max_length=20, verbose_name='Estado General')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Inspector')),
            ],
            options={
                'verbose_name': 'Inspección de Botiquín',
                'verbose_name_plural': 'Inspecciones de Botiquines',
                'ordering': ['-inspection_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirstAidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=100, verbose_name='Elemento')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('status', models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('Vencido', 'Vencido'), ('Incompleto', 'Incompleto')], default='Bueno', max_length=20, verbose_name='Estado')),
                ('observations', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.firstaidinspection')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Fecha de Inspección')),
                ('area', models.CharField(max_length=200, verbose_name='Área/Ubicación')),
                ('general_status', models.CharField(choices=[('Cumple', 'Cumple'), ('No Cumple', 'No Cumple'), ('No Aplica', 'No Aplica')], default='Cumple', max_length=20, verbose_name='Estado General')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Inspector')),
            ],
            options={
                'verbose_name': 'Inspección de Procesos',
                'verbose_name_plural': 'Inspecciones de Procesos',
                'ordering': ['-inspection_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Ítem a Evaluar')),
                ('response', models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('NA', 'No Aplica')], default='Si', max_length=10, verbose_name='Cumple')),
                ('observations', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.processinspection')),
            ],
        ),
        migrations.CreateModel(
            name='StorageInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Fecha de Inspección')),
                ('area', models.CharField(max_length=200, verbose_name='Área/Ubicación')),
                ('general_status', models.CharField(choices=[('Cumple', 'Cumple'), ('No Cumple', 'No Cumple'), ('No Aplica', 'No Aplica')], default='Cumple', max_length=20, verbose_name='Estado General')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Inspector')),
            ],
            options={
                'verbose_name': 'Inspección de Almacenamiento',
                'verbose_name_plural': 'Inspecciones de Almacenamiento',
                'ordering': ['-inspection_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Ítem a Evaluar')),
                ('response', models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('NA', 'No Aplica')], default='Si', max_length=10, verbose_name='Cumple')),
                ('observations', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.storageinspection')),
            ],
        ),
    ]
