# Generated by Django 5.2.7 on 2026-02-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_inspectionschedule_responsible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extinguisherinspection',
            name='inspector_role',
            field=models.CharField(choices=[('Brigadista', 'Brigadista'), ('Equipo SST', 'Equipo SST'), ('Copasst', 'Copasst')], default='Equipo SST', max_length=20, verbose_name='Rol del Inspector'),
        ),
    ]
