# Generated by Django 5.2.7 on 2026-02-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_firstaidinspection_inspector_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcheckitem',
            name='item_status',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('NA', 'No Aplica')], default='Bueno', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='processinspection',
            name='inspected_process',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Proceso Inspeccionado'),
        ),
        migrations.AddField(
            model_name='processinspection',
            name='inspector_role',
            field=models.CharField(choices=[('Brigadista', 'Brigadista'), ('Equipo SST', 'Equipo SST'), ('Copasst', 'Copasst')], default='Equipo SST', max_length=20, verbose_name='Rol del Inspector'),
        ),
        migrations.AlterField(
            model_name='processcheckitem',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Ítem a Evaluar'),
        ),
    ]
