# Generated by Django 5.2.7 on 2026-02-10 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_storagecheckitem_item_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extinguisherinspection',
            name='schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actual_inspections', to='inspections.inspectionschedule', verbose_name='Ítem del Cronograma'),
        ),
        migrations.AddField(
            model_name='firstaidinspection',
            name='schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actual_inspections', to='inspections.inspectionschedule', verbose_name='Ítem del Cronograma'),
        ),
        migrations.AddField(
            model_name='processinspection',
            name='schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actual_inspections', to='inspections.inspectionschedule', verbose_name='Ítem del Cronograma'),
        ),
        migrations.AddField(
            model_name='storageinspection',
            name='schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actual_inspections', to='inspections.inspectionschedule', verbose_name='Ítem del Cronograma'),
        ),
    ]
