# Generated by Django 5.2.7 on 2026-02-10 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_extinguisherinspection_schedule_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForkliftInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Fecha de Inspección')),
                ('area', models.CharField(max_length=200, verbose_name='Área/Ubicación')),
                ('general_status', models.CharField(choices=[('Cumple', 'Cumple'), ('No Cumple', 'No Cumple'), ('No Aplica', 'No Aplica')], default='Cumple', max_length=20, verbose_name='Estado General')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forklift_type', models.CharField(choices=[('Combustible', 'Montacarga de Combustible'), ('Electrico', 'Montacarga Eléctrico')], default='Combustible', max_length=20, verbose_name='Tipo de Montacarga')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Inspector')),
                ('schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actual_inspections', to='inspections.inspectionschedule', verbose_name='Ítem del Cronograma')),
            ],
            options={
                'verbose_name': 'Inspección de Montacargas',
                'verbose_name_plural': 'Inspecciones de Montacargas',
                'ordering': ['-inspection_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForkliftCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Ítem a Evaluar')),
                ('response', models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('NA', 'N/A')], default='Si', max_length=10, verbose_name='Cumple')),
                ('observations', models.CharField(blank=True, max_length=255, verbose_name='Observación')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.forkliftinspection')),
            ],
        ),
    ]
