# Generated by Django 5.2.7 on 2026-02-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extinguisherinspection',
            name='area',
            field=models.ForeignKey(help_text='Seleccione el área inspeccionada', on_delete=django.db.models.deletion.PROTECT, to='inspections.area', verbose_name='Área/Ubicación'),
        ),
        migrations.AlterField(
            model_name='firstaidinspection',
            name='area',
            field=models.ForeignKey(help_text='Seleccione el área inspeccionada', on_delete=django.db.models.deletion.PROTECT, to='inspections.area', verbose_name='Área/Ubicación'),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='area',
            field=models.ForeignKey(help_text='Seleccione el área inspeccionada', on_delete=django.db.models.deletion.PROTECT, to='inspections.area', verbose_name='Área/Ubicación'),
        ),
        migrations.AlterField(
            model_name='inspectionschedule',
            name='area',
            field=models.ForeignKey(help_text='Seleccione el área donde se realizará la inspección', on_delete=django.db.models.deletion.PROTECT, to='inspections.area', verbose_name='Área a Inspeccionar'),
        ),
        migrations.AlterField(
            model_name='processinspection',
            name='area',
            field=models.ForeignKey(help_text='Seleccione el área inspeccionada', on_delete=django.db.models.deletion.PROTECT, to='inspections.area', verbose_name='Área/Ubicación'),
        ),
        migrations.AlterField(
            model_name='storageinspection',
            name='area',
            field=models.ForeignKey(help_text='Seleccione el área inspeccionada', on_delete=django.db.models.deletion.PROTECT, to='inspections.area', verbose_name='Área/Ubicación'),
        ),
    ]
