# Generated by Django 5.2.7 on 2026-02-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_convert_area_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='extinguisheritem',
            name='extinguisher_number',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='extinguisheritem',
            name='extinguisher_type',
            field=models.CharField(choices=[('PQS', 'Polvo Químico Seco (PQS)'), ('AGUA', 'H2O Agua Presión'), ('SOLKAFLAM', 'Solkaflam'), ('CO2', 'CO2 Gas Carbónico'), ('MULTIPROPOSITO', 'Multipropósito ABC')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='inspectionschedule',
            name='frequency',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Cuatrimestral', 'Cuatrimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=20, verbose_name='Frecuencia'),
        ),
    ]
