# Generated by Django 5.2.7 on 2026-02-13 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_extinguisheritem_extinguisher_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extinguisherinspection',
            name='status',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En proceso', 'En proceso'), ('Cerrada', 'Cerrada')], default='En proceso', max_length=20, verbose_name='Estado de Inspección'),
        ),
        migrations.CreateModel(
            name='InspectionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField(verbose_name='Firma Base64 (Snapshot)')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Firma')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='inspections.extinguisherinspection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Firmante')),
            ],
            options={
                'verbose_name': 'Firma de Inspección',
                'verbose_name_plural': 'Firmas de Inspección',
                'unique_together': {('inspection', 'user')},
            },
        ),
    ]
