# Generated by Django 5.2.7 on 2026-02-16 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0012_extinguisherinspection_status_inspectionsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='extinguisherinspection',
            name='parent_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='inspections.extinguisherinspection', verbose_name='Inspección de Origen'),
        ),
        migrations.AlterField(
            model_name='extinguisherinspection',
            name='status',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En proceso', 'En proceso'), ('Cerrada', 'Cerrada'), ('Cerrada con Hallazgos', 'Cerrada con Hallazgos')], default='En proceso', max_length=30, verbose_name='Estado de Inspección'),
        ),
    ]
