# Generated by Django 5.2.7 on 2026-02-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_extinguisherinspection_parent_inspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidinspection',
            name='parent_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='inspections.firstaidinspection', verbose_name='Inspección de Origen'),
        ),
        migrations.AddField(
            model_name='firstaidinspection',
            name='status',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En proceso', 'En proceso'), ('Cerrada', 'Cerrada'), ('Cerrada con Hallazgos', 'Cerrada con Hallazgos'), ('Seguimiento', 'Seguimiento')], default='En proceso', max_length=30, verbose_name='Estado de Inspección'),
        ),
    ]
