# Generated by Django 5.2.7 on 2026-02-16 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0014_firstaidinspection_parent_inspection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField(verbose_name='Firma Base64 (Snapshot)')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Firma')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='inspections.firstaidinspection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Firmante')),
            ],
            options={
                'verbose_name': 'Firma de Inspección de Botiquín',
                'verbose_name_plural': 'Firmas de Inspección de Botiquines',
                'unique_together': {('inspection', 'user')},
            },
        ),
    ]
