# Generated by Django 5.2.7 on 2026-02-17 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0015_firstaidsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinspection',
            name='additional_observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales'),
        ),
        migrations.AddField(
            model_name='processinspection',
            name='parent_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='inspections.processinspection', verbose_name='Inspección Padre'),
        ),
        migrations.AddField(
            model_name='processinspection',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Cerrada', 'Cerrada'), ('Cerrada con Hallazgos', 'Cerrada con Hallazgos'), ('Seguimiento', 'Seguimiento')], default='Pendiente', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='extinguisherinspection',
            name='status',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En proceso', 'En proceso'), ('Cerrada', 'Cerrada'), ('Cerrada con Hallazgos', 'Cerrada con Hallazgos')], default='Programada', max_length=30, verbose_name='Estado de Inspección'),
        ),
        migrations.AlterField(
            model_name='firstaidinspection',
            name='status',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En proceso', 'En proceso'), ('Cerrada', 'Cerrada'), ('Cerrada con Hallazgos', 'Cerrada con Hallazgos'), ('Seguimiento', 'Seguimiento')], default='Programada', max_length=30, verbose_name='Estado de Inspección'),
        ),
    ]
