# Generated by Django 5.2.7 on 2026-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0017_processsignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinspection',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente por ejecutar'), ('En proceso', 'En proceso'), ('Cerrada', 'Cerrada'), ('Cerrada con Hallazgos', 'Cerrada con Hallazgos')], default='Pendiente', max_length=30, verbose_name='Estado'),
        ),
    ]
