# Generated by Django 5.2.7 on 2026-02-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0018_alter_processinspection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processcheckitem',
            name='response',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('NA', 'No Aplica')], default='No', max_length=10, verbose_name='Cumple'),
        ),
    ]
