# Generated by Django 5.2.7 on 2026-02-17 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0019_alter_processcheckitem_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storageinspection',
            name='additional_observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales'),
        ),
        migrations.AddField(
            model_name='storageinspection',
            name='parent_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='inspections.storageinspection', verbose_name='Inspección Padre'),
        ),
        migrations.AddField(
            model_name='storageinspection',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente por ejecutar'), ('Cerrada', 'Cerrada'), ('Cerrada con Hallazgos', 'Cerrada con Hallazgos')], default='Pendiente', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='storagecheckitem',
            name='response',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('NA', 'No Aplica')], default='No', max_length=10, verbose_name='Cumple'),
        ),
        migrations.CreateModel(
            name='StorageSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField(verbose_name='Firma Base64 (Snapshot)')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Firma')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='inspections.storageinspection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Firmante')),
            ],
            options={
                'verbose_name': 'Firma de Inspección de Almacenamiento',
                'verbose_name_plural': 'Firmas de Inspección de Almacenamiento',
                'unique_together': {('inspection', 'user')},
            },
        ),
    ]
