# Generated by Django 5.2.7 on 2026-02-18 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0020_storageinspection_additional_observations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forkliftcheckitem',
            name='item_status',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('NA', 'No Aplica')], default='Bueno', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='forkliftinspection',
            name='additional_observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales'),
        ),
        migrations.AddField(
            model_name='forkliftinspection',
            name='parent_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='inspections.forkliftinspection', verbose_name='Inspección Padre'),
        ),
        migrations.AddField(
            model_name='forkliftinspection',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Cerrada', 'Cerrada'), ('Cerrada con Hallazgos', 'Cerrada con Hallazgos')], default='Pendiente', max_length=30, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ForkliftSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField(verbose_name='Firma Base64 (Snapshot)')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Firma')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='inspections.forkliftinspection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Firmante')),
            ],
            options={
                'verbose_name': 'Firma de Inspección de Montacargas',
                'verbose_name_plural': 'Firmas de Inspección de Montacargas',
                'unique_together': {('inspection', 'user')},
            },
        ),
    ]
