# Generated by Django 5.2.7 on 2026-02-18 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0021_upgrade_forklift_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forkliftinspection',
            name='inspector_role',
            field=models.CharField(choices=[('Brigadista', 'Brigadista'), ('Equipo SST', 'Equipo SST'), ('Copasst', 'Copasst')], default='Equipo SST', max_length=20, verbose_name='Rol del Inspector'),
        ),
        migrations.AlterField(
            model_name='inspectionschedule',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='inspectionschedule',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de Programación'),
        ),
    ]
