# Generated by Django 5.2.7 on 2026-02-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0022_forkliftinspection_inspector_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extinguisheritem',
            name='extinguisher_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
