# Generated by Django 5.2.7 on 2026-02-18 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0023_alter_extinguisheritem_extinguisher_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extinguisheritem',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='firstaiditem',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='forkliftcheckitem',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='processcheckitem',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='storagecheckitem',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='extinguisherinspection',
            name='status',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En proceso', 'En proceso'), ('Pendiente de Firmas', 'Pendiente de Firmas'), ('Cerrada', 'Cerrada'), ('Cerrada con Hallazgos', 'Cerrada con Hallazgos')], default='Programada', max_length=30, verbose_name='Estado de Inspección'),
        ),
        migrations.AlterField(
            model_name='firstaidinspection',
            name='status',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En proceso', 'En proceso'), ('Pendiente de Firmas', 'Pendiente de Firmas'), ('Cerrada', 'Cerrada'), ('Cerrada con Hallazgos', 'Cerrada con Hallazgos'), ('Seguimiento', 'Seguimiento')], default='Programada', max_length=30, verbose_name='Estado de Inspección'),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Pendiente de Firmas', 'Pendiente de Firmas'), ('Cerrada', 'Cerrada'), ('Cerrada con Hallazgos', 'Cerrada con Hallazgos')], default='Pendiente', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='processinspection',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente por ejecutar'), ('En proceso', 'En proceso'), ('Pendiente de Firmas', 'Pendiente de Firmas'), ('Cerrada', 'Cerrada'), ('Cerrada con Hallazgos', 'Cerrada con Hallazgos')], default='Pendiente', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='storageinspection',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente por ejecutar'), ('En proceso', 'En proceso'), ('Pendiente de Firmas', 'Pendiente de Firmas'), ('Cerrada', 'Cerrada'), ('Cerrada con Hallazgos', 'Cerrada con Hallazgos')], default='Pendiente', max_length=30, verbose_name='Estado'),
        ),
    ]
