# Generated by Django 5.2.7 on 2026-02-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0001_initial'),
        ('inspections', '0024_extinguisheritem_registered_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extinguisherinspection',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Activo del inventario asociado a esta inspección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extinguisher_inspections', to='gestion_activos.asset', verbose_name='Activo Relacionado'),
        ),
        migrations.AddField(
            model_name='forkliftinspection',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Activo del inventario asociado a esta inspección', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forklift_inspections', to='gestion_activos.asset', verbose_name='Activo Relacionado'),
        ),
    ]
