# Generated by Django 5.2.7 on 2026-02-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0025_extinguisherinspection_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extinguisheritem',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='extinguisheritem',
            name='extinguisher_number',
        ),
        migrations.RemoveField(
            model_name='extinguisheritem',
            name='extinguisher_type',
        ),
        migrations.RemoveField(
            model_name='extinguisheritem',
            name='last_recharge_date',
        ),
        migrations.RemoveField(
            model_name='extinguisheritem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='extinguisheritem',
            name='next_recharge_date',
        ),
    ]
