# Generated by Django 5.2.7 on 2026-03-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0003_add_tipoextintor_fk_tipoagente'),
        ('inspections', '0026_remove_duplicated_extinguisher_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='extinguisheritem',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extinguisher_items', to='gestion_activos.asset', verbose_name='Extintor (Inventario)'),
        ),
    ]
