# Generated by Django 5.2.7 on 2026-03-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0027_extintor_item_asset_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='extinguisheritem',
            name='fecha_recarga_realizada',
            field=models.DateField(blank=True, help_text='Completar solo si se realizó una recarga durante esta inspección', null=True, verbose_name='Fecha de Recarga Realizada'),
        ),
    ]
