# Generated by Django 5.2.7 on 2026-03-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0028_extintor_item_fecha_recarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='extinguisheritem',
            name='fecha_proxima_recarga',
            field=models.DateField(blank=True, help_text='Calculado: 1 año después de la recarga realizada', null=True, verbose_name='Próxima Recarga'),
        ),
        migrations.AlterField(
            model_name='extinguisherinspection',
            name='status',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En proceso', 'En proceso'), ('Seguimiento en proceso', 'Seguimiento en proceso'), ('Cerrada', 'Cerrada'), ('Cerrada con seguimientos', 'Cerrada con seguimientos')], default='Programada', max_length=30, verbose_name='Estado de Inspección'),
        ),
        migrations.AlterField(
            model_name='firstaidinspection',
            name='status',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En proceso', 'En proceso'), ('Seguimiento en proceso', 'Seguimiento en proceso'), ('Cerrada', 'Cerrada'), ('Cerrada con seguimientos', 'Cerrada con seguimientos')], default='Programada', max_length=30, verbose_name='Estado de Inspección'),
        ),
        migrations.AlterField(
            model_name='forkliftinspection',
            name='status',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En proceso', 'En proceso'), ('Seguimiento en proceso', 'Seguimiento en proceso'), ('Cerrada', 'Cerrada'), ('Cerrada con seguimientos', 'Cerrada con seguimientos')], default='Programada', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='processinspection',
            name='status',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En proceso', 'En proceso'), ('Seguimiento en proceso', 'Seguimiento en proceso'), ('Cerrada', 'Cerrada'), ('Cerrada con seguimientos', 'Cerrada con seguimientos')], default='Programada', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='storageinspection',
            name='status',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En proceso', 'En proceso'), ('Seguimiento en proceso', 'Seguimiento en proceso'), ('Cerrada', 'Cerrada'), ('Cerrada con seguimientos', 'Cerrada con seguimientos')], default='Programada', max_length=30, verbose_name='Estado'),
        ),
    ]
