# Generated by Django 5.2.7 on 2026-03-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0029_extinguisheritem_fecha_proxima_recarga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forkliftinspection',
            name='forklift_type',
            field=models.CharField(blank=True, choices=[('Combustible', 'Montacarga de Combustible'), ('Electrico', 'Montacarga Eléctrico')], default='Combustible', max_length=20, null=True, verbose_name='Tipo de Montacarga'),
        ),
    ]
