# Generated by Django 5.2.7 on 2026-03-05 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inspections', '0030_alter_forkliftinspection_forklift_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='inspections/evidence/%Y/%m/%d/', verbose_name='Imagen de Evidencia')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción o Hallazgo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cargado por')),
            ],
            options={
                'verbose_name': 'Evidencia de Inspección',
                'verbose_name_plural': 'Evidencias de Inspección',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
