# Generated by Django 5.2.7 on 2026-03-10 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0006_add_botiquin_detail'),
        ('inspections', '0031_inspectionevidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forkliftcheckitem',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='storagecheckitem',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='firstaidinspection',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_aid_inspections', to='gestion_activos.asset', verbose_name='Botiquín'),
        ),
    ]
