# Generated by Django 5.2 on 2026-06-22 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0032_add_asset_to_first_aid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extinguisherinspection',
            name='manual_participants',
            field=models.ManyToManyField(blank=True, related_name='manual_extinguisher_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Participantes Adicionales'),
        ),
    ]
