# Generated by Django 5.2 on 2026-06-22 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0033_extinguisherinspection_manual_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidinspection',
            name='manual_participants',
            field=models.ManyToManyField(blank=True, related_name='manual_firstaid_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Participantes Adicionales'),
        ),
        migrations.AddField(
            model_name='forkliftinspection',
            name='manual_participants',
            field=models.ManyToManyField(blank=True, related_name='manual_forklift_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Participantes Adicionales'),
        ),
        migrations.AddField(
            model_name='processinspection',
            name='manual_participants',
            field=models.ManyToManyField(blank=True, related_name='manual_process_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Participantes Adicionales'),
        ),
        migrations.AddField(
            model_name='storageinspection',
            name='manual_participants',
            field=models.ManyToManyField(blank=True, related_name='manual_storage_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Participantes Adicionales'),
        ),
    ]
