# Generated by Django 5.2.7 on 2026-03-24 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_activos', '0007_asset_plano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(db_index=True, help_text='Identificador del plano, ej: PL2P1', max_length=20, verbose_name='Plano')),
                ('posicion_x', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Posición X')),
                ('posicion_y', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Posición Y')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_index=True, default='Activo', max_length=10, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_plano', to='gestion_activos.asset', verbose_name='Activo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Ubicación de Activo en Plano',
                'verbose_name_plural': 'Ubicaciones de Activos en Planos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
