# Generated by Django 5.2.7 on 2026-02-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0024_extinguisheritem_registered_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Activo',
                'verbose_name_plural': 'Tipos de Activo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Activo')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inspections.area', verbose_name='Área')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='gestion_activos.assettype', verbose_name='Tipo de Activo')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExtintorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_agente', models.CharField(max_length=100, verbose_name='Tipo de Agente')),
                ('capacidad_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Capacidad (kg/lbs)')),
                ('fecha_recarga', models.DateField(verbose_name='Fecha de Última Recarga')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extintor_detail', to='gestion_activos.asset', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Detalle de Extintor',
                'verbose_name_plural': 'Detalles de Extintor',
            },
        ),
        migrations.CreateModel(
            name='MontacargasDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, verbose_name='Número de Serie')),
                ('capacidad_carga_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidad de Carga (kg)')),
                ('fecha_ultimo_mantenimiento', models.DateField(verbose_name='Último Mantenimiento')),
                ('fecha_proximo_mantenimiento', models.DateField(verbose_name='Próximo Mantenimiento')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='montacargas_detail', to='gestion_activos.asset', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Detalle de Montacargas',
                'verbose_name_plural': 'Detalles de Montacargas',
            },
        ),
    ]
