# Generated by Django 5.2.7 on 2026-02-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['code'], 'verbose_name': 'Activo', 'verbose_name_plural': 'Activos'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
    ]
