# Generated by Django 5.2.7 on 2026-02-27 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0002_remove_asset_name_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExtintor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Extintor',
                'verbose_name_plural': 'Tipos de Extintor',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='extintordetail',
            name='tipo_agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_activos.tipoextintor', verbose_name='Tipo/Clase de Extintor'),
        ),
    ]
