# Generated by Django 5.2.7 on 2026-03-04 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0003_add_tipoextintor_fk_tipoagente'),
        ('inspections', '0029_extinguisheritem_fecha_proxima_recarga_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='temporal',
            field=models.BooleanField(default=False, verbose_name='Es Temporal'),
        ),
        migrations.AddField(
            model_name='extintordetail',
            name='estado_movimiento',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('REEMPLAZADO', 'Reemplazado'), ('FUERA_DE_SERVICIO', 'Fuera de servicio')], default='NORMAL', max_length=20, verbose_name='Estado de Movimiento'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inspections.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisicion'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='extintordetail',
            name='fecha_recarga',
            field=models.DateField(verbose_name='Fecha de Ultima Recarga'),
        ),
        migrations.AlterField(
            model_name='montacargasdetail',
            name='fecha_proximo_mantenimiento',
            field=models.DateField(verbose_name='Proximo Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='montacargasdetail',
            name='fecha_ultimo_mantenimiento',
            field=models.DateField(verbose_name='Ultimo Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='montacargasdetail',
            name='numero_serie',
            field=models.CharField(max_length=100, verbose_name='Numero de Serie'),
        ),
        migrations.CreateModel(
            name='MovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('salida', 'Salida'), ('reemplazo', 'Reemplazo con Temporal'), ('retorno', 'Retorno del Original'), ('baja_temporal', 'Baja de Temporal')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('fecha', models.DateField(verbose_name='Fecha del Movimiento')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='gestion_activos.asset', verbose_name='Activo')),
                ('activo_relacionado', models.ForeignKey(blank=True, help_text='Temporal asociado en caso de reemplazo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_como_relacionado', to='gestion_activos.asset', verbose_name='Activo Relacionado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Movimiento de Activo',
                'verbose_name_plural': 'Movimientos de Activos',
                'ordering': ['-created_at'],
            },
        ),
    ]
