# Generated by Django 5.2.7 on 2026-03-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0004_movimientos_activos'),
    ]

    operations = [
        migrations.AddField(
            model_name='montacargasdetail',
            name='tipo_montacargas',
            field=models.CharField(choices=[('Combustible', 'Combustible'), ('Electrico', 'Eléctrico')], default='Combustible', max_length=50, verbose_name='Tipo de Montacargas'),
        ),
    ]
