# Generated by Django 5.2.7 on 2026-03-10 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0005_montacargasdetail_tipo_montacargas'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotiquinDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultima_revision', models.DateField(verbose_name='Fecha de Última Revisión / Recarga')),
                ('fecha_proxima_revision', models.DateField(blank=True, help_text='Se calcula automáticamente: +1 año desde la fecha de última revisión.', null=True, verbose_name='Próxima Revisión / Recarga')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='botiquin_detail', to='gestion_activos.asset', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Detalle de Botiquín',
                'verbose_name_plural': 'Detalles de Botiquín',
            },
        ),
    ]
