# Generated by Django 5.2.7 on 2026-03-10 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0006_add_botiquin_detail'),
        ('system_config', '0002_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='system_config.plano', verbose_name='Plano'),
        ),
    ]
