# Generated by Django 5.2.7 on 2026-02-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('users', 'Usuarios'), ('inspections', 'Inspecciones'), ('schedule', 'Cronograma'), ('extinguisher', 'Extintores'), ('first_aid', 'Botiquines'), ('process', 'Procesos'), ('storage', 'Almacenamiento'), ('forklift', 'Montacargas'), ('roles', 'Roles')], max_length=50, verbose_name='Módulo')),
                ('action', models.CharField(choices=[('view', 'Ver módulo'), ('create', 'Registrar'), ('edit', 'Editar'), ('delete', 'Eliminar')], max_length=20, verbose_name='Acción')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['module', 'action'],
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Rol')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_system_role', models.BooleanField(default=False, verbose_name='Rol del Sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='roles.permission', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
    ]
