# Generated by Django 5.2.7 on 2026-02-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', 'Ver módulo'), ('create', 'Registrar'), ('edit', 'Editar'), ('delete', 'Eliminar'), ('reset_password', 'Restablecer Contraseña')], max_length=20, verbose_name='Acción'),
        ),
    ]
