# Generated by Django 5.2.7 on 2026-02-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_permission_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('users', 'Usuarios'), ('inspections', 'Inspecciones'), ('schedule', 'Cronograma'), ('extinguisher', 'Extintores'), ('first_aid', 'Botiquines'), ('process', 'Procesos'), ('storage', 'Almacenamiento'), ('forklift', 'Montacargas'), ('roles', 'Roles'), ('reports', 'Reportes')], max_length=50, verbose_name='Módulo'),
        ),
    ]
