# Generated by Django 5.2.7 on 2026-03-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_alter_permission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', 'Ver módulo'), ('create', 'Registrar'), ('edit', 'Editar'), ('delete', 'Eliminar'), ('reset_password', 'Restablecer Contraseña'), ('gestionar_movimientos', 'Gestionar Movimientos')], max_length=30, verbose_name='Acción'),
        ),
    ]
