# Generated by Django 5.2.7 on 2026-04-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_ampliar_action_y_permiso_movimientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', 'Acceso al módulo'), ('create', 'Registrar'), ('edit', 'Modificar'), ('delete', 'Eliminar'), ('details', 'Consulta'), ('reset_password', 'Restablecer Contraseña'), ('gestionar_movimientos', 'Gestionar Movimientos')], max_length=30, verbose_name='Acción'),
        ),
    ]
