# Generated by Django 5.2 on 2026-06-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0007_alter_permission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('users', 'Usuarios'), ('schedule', 'Cronograma'), ('extinguisher', 'Extintores'), ('first_aid', 'Botiquines'), ('process', 'Procesos'), ('storage', 'Almacenamiento'), ('forklift', 'Montacargas'), ('assets', 'Gestión de Activos'), ('roles', 'Roles'), ('reports', 'Reportes'), ('planos', 'Planos')], max_length=50, verbose_name='Módulo'),
        ),
    ]
