# Generated by Django 5.2.7 on 2026-02-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_extinguisherinspection_inspector_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidinspection',
            name='inspector_role',
            field=models.CharField(choices=[('Brigadista', 'Brigadista'), ('Equipo SST', 'Equipo SST'), ('Copasst', 'Copasst')], default='Equipo SST', max_length=20, verbose_name='Rol del Inspector'),
        ),
        migrations.AlterField(
            model_name='firstaiditem',
            name='element_name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Elemento'),
        ),
        migrations.AlterField(
            model_name='firstaiditem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='firstaiditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad (Unidad)'),
        ),
        migrations.AlterField(
            model_name='firstaiditem',
            name='status',
            field=models.CharField(choices=[('Existe', 'Existe'), ('No Existe', 'No Existe')], default='Existe', max_length=20, verbose_name='Estado'),
        ),
    ]
