# Generated by Django 5.2.7 on 2026-02-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='digital_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Digital'),
        ),
    ]
